### ISSUE TITLE
Blue SAM defences

### ISSUE THREAD

**Issue by Floydii** [Shark149/161SQN-RoW#10]
One Patriot Battery in the depth of the Blue side to keep enemy CAP at bay in depth and two NASAMs Troops (Radar, CP vehicle and 3 launchers) generally in vicinity of the forward FARPS. Coverage should extend 1-2NM over PL Blue.

Suggest these are baked into the mission and not random.

**Comment by Shark149** [comment]
Added to V0.99D

**Comment by Floydii** [comment]
Add M818 (or equiv 'ammo' truck) to Blue SAM Btys for rearm.
