### ISSUE TITLE
Mission Freqs

### ISSUE THREAD

**Issue by Floydii** [Shark149/161SQN-RoW#11]
Current briefed freqs are in some cases too high for some aircraft _or_ use decimals other than .5 - This presents an issue for A/C that cannot readily tune to those decimals.

Suggested changes :

Common Frequencies:

General Air  = 253 AM (as is tradition)

 Air to Helo = 225.5AM

**Comment by Shark149** [comment]
All helos and planes with non-tuneable radios updated in 0.99d
