### ISSUE TITLE
BUG - Remove spawning ammo boxes at FARP rearm pad

### ISSUE THREAD

**Issue by Floydii** [Shark149/161SQN-RoW#14]
The spawning boxes look great.. until you land while they are invisible and they spawn into you..

Suggest they are left off spawned permanently.

Case in point:
![image](https://user-images.githubusercontent.com/40154322/133890408-78dca1e3-7b57-47a3-bd69-9d39932c74c8.png)

**Comment by Shark149** [comment]
Whilst the single helipads look good, i cannot turn off the ammo boxes. Removed the pads from all FARPS in V0.99E

**Comment by Floydii** [comment]
The appearing boxes are part of the single pad by default?
