### ISSUE TITLE
BUG - FARP Truck orientation needs to be adjusted 90 degrees

### ISSUE THREAD

**Issue by Floydii** [Shark149/161SQN-RoW#15]
two of the truck pairs on the FARPs have the following issue with clipping into each other:

![image](https://user-images.githubusercontent.com/40154322/133890545-87c359e5-77ae-415e-a686-1a137805f76f.png)

**Comment by Shark149** [comment]
Moose spawning issue with headings - Workaround implemented in V0.99E
