### ISSUE TITLE
Artillery

### ISSUE THREAD

**Issue by Shark149** [Shark149/161SQN-RoW#6]
- Include Artillery that moves to a zone that puts it about 2/3 of the way towards the current front line. It then proceeds to fire  at any detected ground units. Ideally units report they are under artillery fire and report the rough origin eg: "This is Tango 2-0, taking artillery fire from vicinity CA23, request support, over". Bonus points if it then puts a mark on the map over that square. Arty composition should be about 3-4 Guns (M109 for blue and 2S3 or 2S19 for Red) and an ammo truck.

**Comment by Floydii** [comment]
Additional, have two templates for each Platoon, one of which has an Avenger/SA13 or a Vulcan/Shilka attached.

A more realistic option is spawning a MANPAD when the Unit reaches its location, then despawning it when it relocates or is destroyed. This would remove the need for attached AD vehicles.

**Comment by Shark149** [comment]
Arty implemented within the limits of Moose and Frames
